"""
Migration Script - Upgrade zu höheren Dimensionen für bessere Qualität.

Dieses Script:
1. Zeigt verfügbare Konfigurationen
2. Erstellt neue Datenbank mit höheren Dimensionen
3. Optional: Migriert bestehende Daten
"""

import sys
import os
import logging
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from neuron_system.config.model_configs import (
    print_available_configs,
    get_config,
    AVAILABLE_CONFIGS
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def main():
    """Main migration function."""
    
    print("\n" + "=" * 70)
    print("DIMENSION UPGRADE - Bessere Qualität durch mehr Dimensionen")
    print("=" * 70 + "\n")
    
    # Show current setup
    print("Aktuelles Setup:")
    print("-" * 70)
    print("  Embedding Dim: 384 (all-MiniLM-L6-v2)")
    print("  Qualität: ⭐⭐⭐ Gut")
    print("  Datenbank: neuron_system.db")
    print()
    
    # Show available configs
    print_available_configs()
    
    # Get user choice
    print("Wähle neue Konfiguration:")
    print("  [1] MEDIUM - 768 Dimensionen (EMPFOHLEN)")
    print("  [2] LARGE - 768 Dimensionen + RoBERTa")
    print("  [3] XLARGE - 1024 Dimensionen (Maximum)")
    print("  [0] Abbrechen")
    print()
    
    choice = input("Deine Wahl [1]: ").strip() or "1"
    
    if choice == "0":
        print("Abgebrochen.")
        return
    
    config_map = {
        "1": "medium",
        "2": "large",
        "3": "xlarge"
    }
    
    if choice not in config_map:
        print(f"Ungültige Wahl: {choice}")
        return
    
    config_name = config_map[choice]
    config = get_config(config_name)
    
    print("\n" + "=" * 70)
    print(f"UPGRADE ZU: {config_name.upper()}")
    print("=" * 70)
    print(f"  Embedding Dim: {config.embedding_dim}")
    print(f"  Qualität: {config.quality}")
    print(f"  Speed: {config.speed}")
    print(f"  Memory: ~{config.memory_mb}MB")
    print()
    
    # Create new database name
    new_db_name = f"neuron_system_{config.embedding_dim}d.db"
    
    print(f"Neue Datenbank: {new_db_name}")
    print()
    
    # Check if file exists
    if Path(new_db_name).exists():
        overwrite = input(f"{new_db_name} existiert bereits. Überschreiben? [y/N]: ").strip().lower()
        if overwrite != 'y':
            print("Abgebrochen.")
            return
        Path(new_db_name).unlink()
    
    # Create configuration file
    config_file = "neuron_system_config.py"
    
    config_content = f'''"""
Auto-generated configuration for {config.embedding_dim}D system.
Generated by migrate_to_higher_dimensions.py
"""

# Model Configuration
EMBEDDING_DIM = {config.embedding_dim}
SENTENCE_TRANSFORMER_MODEL = "{config.sentence_transformer}"
PRETRAINED_MODEL = "{config.pretrained_model}"

# Database
DATABASE_PATH = "{new_db_name}"

# Neural Inference
NUM_ATTENTION_HEADS = {6 if config.embedding_dim <= 768 else 8}
HIDDEN_DIM = {config.embedding_dim * 2}

# Info
CONFIG_NAME = "{config_name}"
DESCRIPTION = "{config.description}"
'''
    
    with open(config_file, 'w', encoding='utf-8') as f:
        f.write(config_content)
    
    print(f"✓ Konfiguration erstellt: {config_file}")
    print()
    
    # Create example usage script
    example_script = f'''"""
Beispiel: Nutze das neue {config.embedding_dim}D System
"""

from neuron_system.core.graph import NeuronGraph
from neuron_system.engines.compression import CompressionEngine
from neuron_system.engines.query import QueryEngine
from neuron_system.engines.training import TrainingEngine
from neuron_system.ai.smart_language_model import SmartLanguageModel
from neuron_system.storage.database import DatabaseManager

# Import config
from neuron_system_config import *

# Initialize with new dimensions
print(f"Initializing {{EMBEDDING_DIM}}D system...")

# Database
db_manager = DatabaseManager(DATABASE_PATH)

# Graph
graph = NeuronGraph()
graph.attach_storage(db_manager)

# Engines
compression_engine = CompressionEngine(model_name=SENTENCE_TRANSFORMER_MODEL)
query_engine = QueryEngine(graph, compression_engine)
training_engine = TrainingEngine(graph)

# Smart Language Model
model = SmartLanguageModel(
    graph=graph,
    compression_engine=compression_engine,
    query_engine=query_engine,
    training_engine=training_engine,
    pretrained_model=PRETRAINED_MODEL
)

print(f"✓ {{EMBEDDING_DIM}}D System ready!")
print(f"  Config: {{CONFIG_NAME}}")
print(f"  Database: {{DATABASE_PATH}}")
print(f"  Quality: {config.quality}")

# Train
print("\\nTraining...")
model.learn(
    text="Question: What is AI? Answer: Artificial Intelligence is the simulation of human intelligence by machines.",
    tags=['ai', 'definition']
)

# Query
print("\\nQuerying...")
response = model.generate_response("What is AI?")
print(f"Response: {{response}}")
'''
    
    example_file = f"example_{config.embedding_dim}d.py"
    with open(example_file, 'w', encoding='utf-8') as f:
        f.write(example_script)
    
    print(f"✓ Beispiel-Script erstellt: {example_file}")
    print()
    
    # Summary
    print("=" * 70)
    print("UPGRADE COMPLETE!")
    print("=" * 70)
    print()
    print("Nächste Schritte:")
    print(f"  1. Teste das neue System: python {example_file}")
    print(f"  2. Trainiere mit deinen Daten")
    print(f"  3. Vergleiche Qualität mit altem System")
    print()
    print("Vorteile:")
    print(f"  ✓ {config.embedding_dim} Dimensionen (vorher: 384)")
    print(f"  ✓ Bessere Qualität: {config.quality}")
    print(f"  ✓ Mehr Informationsdichte")
    print(f"  ✓ Besseres kontextuelles Verständnis")
    print()
    print("Hinweis:")
    print("  - Alte Datenbank (neuron_system.db) bleibt erhalten")
    print("  - Du kannst beide Systeme parallel nutzen")
    print("  - Migration von Daten ist optional")
    print()
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()
